---
- name: Update apt repo and cache
  apt: update_cache=yes

- name: Install requirements
  apt:
    name: libguestfs-tools

- name: Download cloud image
  register: reg_download_image
  get_url:
    url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
    dest: /var/lib/vz/images/ubuntu-2204-jammy-server-cloudimg-amd64.img

- name: Create template
  when: reg_download_image.changed == true
  vars:
    vmid: 9001
    storage_name: fast1
    file_name: ubuntu-2204-jammy-server-cloudimg-amd64.img
    template_name: ubuntu-2204-cloudinit-template
  shell:
    chdir: /var/lib/vz/images
    cmd: |
      virt-customize -a {{ file_name }} --install qemu-guest-agent 
      qm create {{ vmid }} --name "{{ template_name }}" --memory 2048 --cores 2 --net0 virtio,bridge=vmbr0 
      qm importdisk {{ vmid }} {{ file_name }} {{ storage_name }}
      qm set {{ vmid }} --scsihw virtio-scsi-pci --scsi0 {{ storage_name }}:vm-{{ vmid }}-disk-0
      qm set {{ vmid }} --boot c --bootdisk scsi0
      qm set {{ vmid }} --ide2 {{ storage_name }}:cloudinit
      qm set {{ vmid }} --serial0 socket --vga serial0
      qm set {{ vmid }} --agent enabled=1
      qm template {{ vmid }}