---
- name: Create Template
  include_tasks: "{{ item.key }}.yml"
  vars:
    vmid: "{{ item.vmid }}"
    imageUrl: "{{ item.imageUrl }}"
    key: "{{ item.key }}"
    storage_name: "{{ item.storage_name }}"
    template_name: "{{ item.template_name }}"

  with_items: "{{ templates }}"
